yolo_model:

  config_file:
    name: yolov3-tiny-usm.cfg
  weight_file:
    name: yolov3-tiny-usm_16000.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - pipe
      - docking station